
services:
  k6:
    build: ./load-tests
    container_name: k6_staging
    networks:
      - staging_network
    entrypoint: [ "k6" ]
    command: ["run",  "--out", "json=/load-tests/results.json",  "--out","cloud",  "/load-tests/staging-load.js"]

networks:
  staging_network:
    external: true
