
services:
  k6:
    build: ./load-tests
    container_name: k6_staging
    networks:
      - staging_network
    entrypoint: [ "k6" ]
    command: ["run", "--vus" , "50",  "--out", "json=/load-tests/results.json", "/load-tests/staging-load.js", "--out","cloud"]

networks:
  staging_network:
    external: true
